-- Create companies table and seed from companies.json

CREATE TABLE IF NOT EXISTS companies (
    slug    TEXT PRIMARY KEY,
    name    TEXT NOT NULL,
    ats     TEXT,
    board   TEXT,
    config  JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_companies_ats ON companies (ats) WHERE ats IS NOT NULL;

-- 540 companies from companies.json
INSERT INTO companies (slug, name, ats, board, config) VALUES
  ('adobe', 'Adobe', 'workday', 'external_experienced', '{"wd_company": "adobe", "wd_instance": 5}'::jsonb),
  ('aftership', 'AfterShip', 'greenhouse', 'aftership', '{}'::jsonb),
  ('ai2', 'AI2', NULL, NULL, '{}'::jsonb),
  ('aim-consulting', 'AIM Consulting', NULL, NULL, '{}'::jsonb),
  ('airtable', 'Airtable', 'greenhouse', 'airtable', '{}'::jsonb),
  ('akasa', 'Akasa', 'ashby', 'akasa', '{}'::jsonb),
  ('amazon', 'Amazon', NULL, NULL, '{}'::jsonb),
  ('amperity', 'Amperity', 'greenhouse', 'amperity', '{}'::jsonb),
  ('anduril', 'Anduril', 'greenhouse', 'andurilindustries', '{}'::jsonb),
  ('anthropic', 'Anthropic', 'greenhouse', 'anthropic', '{}'::jsonb),
  ('apple', 'Apple', NULL, NULL, '{}'::jsonb),
  ('authenticx', 'Authenticx', NULL, NULL, '{}'::jsonb),
  ('autofi', 'AutoFi', NULL, NULL, '{}'::jsonb),
  ('automattic', 'Automattic', NULL, NULL, '{}'::jsonb),
  ('axon', 'Axon', 'greenhouse', 'axon', '{}'::jsonb),
  ('baseten', 'Baseten', 'ashby', 'baseten', '{}'::jsonb),
  ('blueorigin', 'BlueOrigin', 'workday', 'BlueOrigin', '{"default_filters": {"appliedFacets": {"jobFamilyGroup": ["5f32d2b8465201de6df43ce63e17db4f", "5f32d2b8465201d3591aab963e17074f"]}}, "wd_company": "blueorigin", "wd_instance": 5}'::jsonb),
  ('blurb', 'Blurb', NULL, NULL, '{}'::jsonb),
  ('boston-consulting-group', 'Boston Consulting Group', NULL, NULL, '{}'::jsonb),
  ('checkr', 'Checkr', 'greenhouse', 'checkr', '{}'::jsonb),
  ('chronicle-of-higher-education', 'Chronicle of Higher Education', NULL, NULL, '{}'::jsonb),
  ('cisco', 'Cisco', NULL, NULL, '{}'::jsonb),
  ('clear', 'CLEAR', 'greenhouse', 'clear', '{}'::jsonb),
  ('cloudflare', 'Cloudflare', 'greenhouse', 'cloudflare', '{}'::jsonb),
  ('cohere', 'Cohere', 'ashby', 'cohere', '{}'::jsonb),
  ('coinbase', 'Coinbase', 'greenhouse', 'coinbase', '{}'::jsonb),
  ('column', 'Column', NULL, NULL, '{}'::jsonb),
  ('convoy', 'Convoy', NULL, NULL, '{}'::jsonb),
  ('creditkarma', 'Credit Karma', 'greenhouse', 'creditkarma', '{}'::jsonb),
  ('crown-castle', 'Crown Castle', NULL, NULL, '{}'::jsonb),
  ('crusoe', 'Crusoe', 'ashby', 'Crusoe', '{}'::jsonb),
  ('curate-partners', 'Curate Partners', NULL, NULL, '{}'::jsonb),
  ('databricks', 'Databricks', 'greenhouse', 'databricks', '{}'::jsonb),
  ('datadog', 'Datadog', 'greenhouse', 'datadog', '{}'::jsonb),
  ('datarobot', 'DataRobot', 'workday', 'DataRobot_External_Careers', '{"wd_company": "datarobot", "wd_instance": 1}'::jsonb),
  ('deepmind', 'DeepMind', 'greenhouse', 'deepmind', '{}'::jsonb),
  ('dice', 'Dice', NULL, NULL, '{}'::jsonb),
  ('discord', 'Discord', 'greenhouse', 'discord', '{}'::jsonb),
  ('disney', 'Disney', NULL, NULL, '{}'::jsonb),
  ('docusign', 'Docusign', NULL, NULL, '{}'::jsonb),
  ('doordash', 'DoorDash', 'greenhouse', 'doordashusa', '{}'::jsonb),
  ('dronedeploy', 'DroneDeploy', NULL, NULL, '{}'::jsonb),
  ('dropbox', 'Dropbox', 'greenhouse', 'dropbox', '{}'::jsonb),
  ('duolingo', 'Duolingo', 'greenhouse', 'duolingo', '{}'::jsonb),
  ('duranta', 'Duranta', 'lever', 'getduranta', '{}'::jsonb),
  ('ebay', 'eBay', NULL, NULL, '{}'::jsonb),
  ('expedia', 'Expedia', 'workday', 'search', '{"wd_company": "expedia", "wd_instance": 108}'::jsonb),
  ('ey', 'EY', NULL, NULL, '{}'::jsonb),
  ('f5', 'F5', 'workday', 'f5jobs', '{"wd_company": "ffive", "wd_instance": 5}'::jsonb),
  ('financialforce', 'FinancialForce', NULL, NULL, '{}'::jsonb),
  ('flexport', 'Flexport', 'greenhouse', 'flexport', '{}'::jsonb),
  ('float', 'Float', NULL, NULL, '{}'::jsonb),
  ('fluidstack', 'Fluidstack', NULL, NULL, '{}'::jsonb),
  ('friends-of-kexp', 'Friends of KEXP', 'paylocity', 'a5fc1657-6a0e-4279-b56f-f2c46121f3f5', '{"company_slug": "Friends-of-KEXP"}'::jsonb),
  ('fusionbox', 'Fusionbox', NULL, NULL, '{}'::jsonb),
  ('gitlab', 'GitLab', 'greenhouse', 'gitlab', '{}'::jsonb),
  ('glean', 'Glean', 'greenhouse', 'gleanwork', '{}'::jsonb),
  ('google', 'Google', NULL, NULL, '{}'::jsonb),
  ('graphite', 'Graphite', NULL, NULL, '{}'::jsonb),
  ('gsk-onyx', 'GSK / Onyx', NULL, NULL, '{}'::jsonb),
  ('headway', 'Headway', 'greenhouse', 'headway', '{}'::jsonb),
  ('highspot', 'Highspot', 'lever', 'highspot', '{}'::jsonb),
  ('hp', 'HP', 'workday', 'EXTEU-AC-CareerSite', '{"default_filters": {"appliedFacets": {"Location_Country": ["bc33aa3152ec42d4995f4791a106ed09"]}}, "wd_company": "hp", "wd_instance": 5}'::jsonb),
  ('hs', 'Headspace', 'greenhouse', 'hs', '{}'::jsonb),
  ('huggingface', 'Hugging Face', 'workable', 'huggingface', '{}'::jsonb),
  ('ifm', 'Institute of Foundation Models', 'lever', 'ifm-us', '{}'::jsonb),
  ('imprint', 'Imprint', 'ashby', 'imprint', '{}'::jsonb),
  ('incode', 'Incode', NULL, NULL, '{}'::jsonb),
  ('intuit', 'Intuit', 'talentbrew', NULL, '{"tb_host": "jobs.intuit.com", "tb_tenant_id": 27595}'::jsonb),
  ('koidra', 'Koidra', NULL, NULL, '{}'::jsonb),
  ('lambda', 'Lambda', 'ashby', 'lambda', '{}'::jsonb),
  ('levelten-energy', 'LevelTen Energy', NULL, NULL, '{}'::jsonb),
  ('linear', 'Linear', 'ashby', 'Linear', '{}'::jsonb),
  ('liveramp', 'LiveRamp', 'workday', 'LiveRampCareers', '{"wd_company": "liveramp", "wd_instance": 5}'::jsonb),
  ('mason', 'Mason', NULL, NULL, '{}'::jsonb),
  ('meta', 'Meta', NULL, NULL, '{}'::jsonb),
  ('metropolis', 'Metropolis', 'greenhouse', 'metropolis', '{}'::jsonb),
  ('microsoft', 'Microsoft', 'eightfold', 'microsoft', '{"base_url": "https://apply.careers.microsoft.com", "default_filters": {"location": "United States"}, "domain": "microsoft.com"}'::jsonb),
  ('mithril', 'Mithril', 'greenhouse', 'mithril', '{}'::jsonb),
  ('moderna', 'Moderna', NULL, NULL, '{}'::jsonb),
  ('moloco', 'Moloco', 'greenhouse', 'moloco', '{}'::jsonb),
  ('moment', 'Moment', 'greenhouse', 'momentmarkets', '{}'::jsonb),
  ('moody-s', 'Moody''s', NULL, NULL, '{}'::jsonb),
  ('moody-s-nw-consulting', 'Moody''s NW Consulting', NULL, NULL, '{}'::jsonb),
  ('morgan-morgan', 'Morgan & Morgan', 'greenhouse', 'morganmorganjobsapplynow', '{}'::jsonb),
  ('nimbus', 'Nimbus', NULL, NULL, '{}'::jsonb),
  ('notion', 'Notion', 'ashby', 'notion', '{}'::jsonb),
  ('nvidia', 'NVIDIA', 'workday', 'NVIDIAExternalCareerSite', '{"default_filters": {"appliedFacets": {"jobFamilyGroup": ["0c40f6bd1d8f10ae43ffaefd46dc7e78", "0c40f6bd1d8f10ae43ffc668c6847e8c"]}}, "wd_company": "nvidia", "wd_instance": 5}'::jsonb),
  ('openai', 'OpenAI', 'ashby', 'openai', '{}'::jsonb),
  ('oracle', 'Oracle', 'oracle_hcm', 'eeho', '{"default_filters": {"categories": ["300000001917356", "300000001917346", "302958497961746"], "location": "United States"}, "ohcm_region": "us2", "site_number": "CX_1", "site_slug": "jobsearch"}'::jsonb),
  ('otter', 'Otter', 'greenhouse', 'otter', '{}'::jsonb),
  ('oura', 'Oura', 'greenhouse', 'oura', '{}'::jsonb),
  ('outreach', 'Outreach', 'lever', 'outreach', '{}'::jsonb),
  ('palantir', 'Palantir', 'lever', 'palantir', '{}'::jsonb),
  ('paylocity', 'Paylocity', 'paylocity', 'e2bcef5a-b6e5-4c5a-8fdd-c4da179dd98c', '{"ats_prefix": "2000", "company_slug": "Paylocity"}'::jsonb),
  ('paypal', 'PayPal', 'workday', 'jobs', '{"wd_company": "paypal", "wd_instance": 1}'::jsonb),
  ('perplexity', 'Perplexity', 'ashby', 'perplexity', '{}'::jsonb),
  ('peregrine', 'Peregrine', 'greenhouse', 'peregrinetechnologies', '{}'::jsonb),
  ('phillips', 'Phillips', NULL, NULL, '{}'::jsonb),
  ('pioneer-square-labs', 'Pioneer Square Labs', NULL, NULL, '{}'::jsonb),
  ('pitchbook', 'Pitchbook', 'greenhouse', 'pitchbookdata', '{}'::jsonb),
  ('plaid', 'Plaid', 'lever', 'plaid', '{}'::jsonb),
  ('posthog', 'PostHog', 'ashby', 'posthog', '{}'::jsonb),
  ('prophecy', 'Prophecy', 'greenhouse', 'prophecysimpledatalabs', '{}'::jsonb),
  ('pwc', 'PwC', NULL, NULL, '{}'::jsonb),
  ('qualtrics', 'Qualtrics', 'greenhouse', 'qualtrics', '{}'::jsonb),
  ('qumulo', 'Qumulo', NULL, NULL, '{}'::jsonb),
  ('ramp', 'Ramp', 'ashby', 'ramp', '{}'::jsonb),
  ('reddit', 'Reddit', 'greenhouse', 'reddit', '{}'::jsonb),
  ('rei', 'REI', NULL, NULL, '{}'::jsonb),
  ('remitly', 'Remitly', NULL, NULL, '{}'::jsonb),
  ('replit', 'Replit', 'ashby', 'replit', '{}'::jsonb),
  ('rentspree', 'RentSpree', 'rippling', 'rentspree', '{}'::jsonb),
  ('rippling', 'Rippling', 'rippling', 'rippling', '{}'::jsonb),
  ('robinhood', 'Robinhood', 'greenhouse', 'robinhood', '{}'::jsonb),
  ('salesforce', 'Salesforce', 'workday', 'External_Career_Site', '{"wd_company": "salesforce", "wd_instance": 12}'::jsonb),
  ('scholarly', 'Scholarly', 'ashby', 'Scholarly', '{}'::jsonb),
  ('shantui-america-corp', 'SHANTUI AMERICA CORP', NULL, NULL, '{}'::jsonb),
  ('sentry', 'Sentry', 'ashby', 'sentry', '{}'::jsonb),
  ('sentinelone', 'SentinelOne', 'greenhouse', 'sentinellabs', '{}'::jsonb),
  ('silkline', 'Silkline', NULL, NULL, '{}'::jsonb),
  ('snowflake', 'Snowflake', 'ashby', 'snowflake', '{}'::jsonb),
  ('sofi', 'SoFi', 'greenhouse', 'sofi', '{}'::jsonb),
  ('sonos', 'Sonos', NULL, NULL, '{}'::jsonb),
  ('sphinx', 'Sphinx', 'greenhouse', 'sphinxdefense', '{}'::jsonb),
  ('spotify', 'Spotify', 'lever', 'spotify', '{}'::jsonb),
  ('spring-health', 'Spring Health', 'greenhouse', 'springhealth66', '{}'::jsonb),
  ('stack-influence', 'Stack Influence', NULL, NULL, '{}'::jsonb),
  ('stainless', 'Stainless', 'ashby', 'stainlessapi', '{}'::jsonb),
  ('starbucks', 'Starbucks', 'eightfold', 'starbucks', '{"base_url": "https://apply.starbucks.com", "default_filters": {"filter_job_category": ["technology", "business strategy"], "location": "WA, United States"}, "domain": "starbucks.com"}'::jsonb),
  ('striveworks', 'Striveworks', 'greenhouse', 'striveworks', '{}'::jsonb),
  ('stripe', 'Stripe', 'greenhouse', 'stripe', '{}'::jsonb),
  ('t-mobile', 'T-Mobile', 'workday', 'External', '{"default_filters": {"appliedFacets": {"Job_Family_Group": ["426b19690b7b1036f85c9c0f4dd30a29", "426b19690b7b1036f85d91748cc80a51", "426b19690b7b1036f85cd4aeae300a33", "426b19690b7b1036f85d16cd22eb0a49"]}}, "wd_company": "tmobile", "wd_instance": 1}'::jsonb),
  ('the-room', 'The Room', NULL, NULL, '{}'::jsonb),
  ('thealleninstitute', 'Allen Institute for AI', 'greenhouse', 'thealleninstitute', '{}'::jsonb),
  ('thetradedesk', 'The Trade Desk', 'greenhouse', 'thetradedesk', '{}'::jsonb),
  ('thousandeyes', 'ThousandEyes', NULL, NULL, '{}'::jsonb),
  ('tiktok', 'TikTok', NULL, NULL, '{}'::jsonb),
  ('trucksmarter', 'TruckSmarter', 'ashby', 'trucksmarter', '{}'::jsonb),
  ('twilio', 'Twilio', 'greenhouse', 'twilio', '{}'::jsonb),
  ('tubitv', 'Tubi', 'greenhouse', 'tubitv', '{}'::jsonb),
  ('twitch', 'Twitch', 'greenhouse', 'twitch', '{}'::jsonb),
  ('typeface', 'Typeface', 'greenhouse', 'typeface', '{}'::jsonb),
  ('uber', 'Uber', NULL, NULL, '{}'::jsonb),
  ('unframe', 'Unframe', 'greenhouse', 'unframe', '{}'::jsonb),
  ('unitq', 'unitQ', 'lever', 'unitq', '{}'::jsonb),
  ('university-of-washington', 'University of Washington', NULL, NULL, '{}'::jsonb),
  ('us-bank', 'US Bank', NULL, NULL, '{}'::jsonb),
  ('vanta', 'Vanta', 'ashby', 'vanta', '{}'::jsonb),
  ('vbeyond-corporation', 'VBeyond Corporation', NULL, NULL, '{}'::jsonb),
  ('vestwell', 'Vestwell', NULL, NULL, '{}'::jsonb),
  ('walmart', 'Walmart', 'workday', 'WalmartExternal', '{"default_filters": {"appliedFacets": {"jobFamilyGroup": ["e83ebdbd2a0a01e7e1477a8948e904c6", "e83ebdbd2a0a01af0185848948e94dc6", "e83ebdbd2a0a01769a8c8b8948e96cc6", "e83ebdbd2a0a01ea72c2808948e924c6", "e83ebdbd2a0a01cc71e67f8948e91ac6"]}}, "wd_company": "walmart", "wd_instance": 5}'::jsonb),
  ('warner-bros-discovery', 'Warner Bros. Discovery', NULL, NULL, '{}'::jsonb),
  ('waymo', 'Waymo', 'greenhouse', 'waymo', '{}'::jsonb),
  ('wellsaid-labs', 'WellSaid Labs', NULL, NULL, '{}'::jsonb),
  ('wibotic', 'WiBotic', NULL, NULL, '{}'::jsonb),
  ('workato', 'Workato', 'greenhouse', 'workato', '{}'::jsonb),
  ('workday', 'Workday', 'workday', 'Workday', '{"wd_company": "workday", "wd_instance": 5}'::jsonb),
  ('zoom', 'Zoom', 'workday', 'Zoom', '{"wd_company": "zoom", "wd_instance": 5}'::jsonb),
  ('zoox', 'Zoox', 'lever', 'zoox', '{}'::jsonb),
  ('pagerduty', 'PagerDuty', 'greenhouse', 'pagerduty', '{}'::jsonb),
  ('zscaler', 'Zscaler', 'greenhouse', 'zscaler', '{}'::jsonb),
  ('affirm', 'Affirm', 'greenhouse', 'affirm', '{}'::jsonb),
  ('remotecom', 'Remote', 'greenhouse', 'remotecom', '{}'::jsonb),
  ('gusto', 'Gusto', 'greenhouse', 'gusto', '{}'::jsonb),
  ('verkada', 'Verkada', 'greenhouse', 'verkada', '{}'::jsonb),
  ('scaleai', 'Scale AI', 'greenhouse', 'scaleai', '{}'::jsonb),
  ('anyscale', 'Anyscale', 'ashby', 'anyscale', '{}'::jsonb),
  ('sambanova', 'SambaNova', 'ashby', 'sambanova', '{}'::jsonb),
  ('cursor', 'Cursor', 'ashby', 'cursor', '{}'::jsonb),
  ('aurorainnovation', 'Aurora Innovation', 'greenhouse', 'aurorainnovation', '{}'::jsonb),
  ('toast', 'Toast', 'greenhouse', 'toast', '{}'::jsonb),
  ('asana', 'Asana', 'greenhouse', 'asana', '{}'::jsonb),
  ('hubspot', 'HubSpot', 'greenhouse', 'hubspotjobs', '{}'::jsonb),
  ('netlify', 'Netlify', 'greenhouse', 'netlify', '{}'::jsonb),
  ('vercel', 'Vercel', 'greenhouse', 'vercel', '{}'::jsonb),
  ('wiz', 'Wiz', 'greenhouse', 'wizinc', '{}'::jsonb),
  ('dbt-labs', 'dbt Labs', 'greenhouse', 'dbtlabsinc', '{}'::jsonb),
  ('amplitude', 'Amplitude', 'greenhouse', 'amplitude', '{}'::jsonb),
  ('appian', 'Appian', 'greenhouse', 'appian', '{}'::jsonb),
  ('applovin', 'AppLovin', 'greenhouse', 'applovin', '{}'::jsonb),
  ('braze', 'Braze', 'greenhouse', 'braze', '{}'::jsonb),
  ('buildkite', 'Buildkite', 'greenhouse', 'buildkite', '{}'::jsonb),
  ('carta', 'Carta', 'greenhouse', 'carta', '{}'::jsonb),
  ('chime', 'Chime', 'greenhouse', 'chime', '{}'::jsonb),
  ('circleci', 'CircleCI', 'greenhouse', 'circleci', '{}'::jsonb),
  ('contentful', 'Contentful', 'greenhouse', 'contentful', '{}'::jsonb),
  ('coupang', 'Coupang', 'greenhouse', 'coupang', '{}'::jsonb),
  ('coursera', 'Coursera', 'greenhouse', 'coursera', '{}'::jsonb),
  ('dataiku', 'Dataiku', 'greenhouse', 'dataiku', '{}'::jsonb),
  ('descript', 'Descript', 'greenhouse', 'descript', '{}'::jsonb),
  ('elastic', 'Elastic', 'greenhouse', 'elastic', '{}'::jsonb),
  ('epicgames', 'Epic Games', 'greenhouse', 'epicgames', '{}'::jsonb),
  ('fastly', 'Fastly', 'greenhouse', 'fastly', '{}'::jsonb),
  ('fivetran', 'Fivetran', 'greenhouse', 'fivetran', '{}'::jsonb),
  ('forter', 'Forter', 'greenhouse', 'forter', '{}'::jsonb),
  ('grafana-labs', 'Grafana Labs', 'greenhouse', 'grafanalabs', '{}'::jsonb),
  ('honeycomb', 'Honeycomb', 'greenhouse', 'honeycomb', '{}'::jsonb),
  ('instacart', 'Instacart', 'greenhouse', 'instacart', '{}'::jsonb),
  ('jpmc', 'JPMorgan Chase', 'oracle_hcm', 'jpmc', '{"default_filters": {"categories": ["300000086152753", "300000086251864"], "location": "United States"}, "site_number": "CX_1001", "site_slug": "CX_1001"}'::jsonb),
  ('justworks', 'Justworks', 'greenhouse', 'justworks', '{}'::jsonb),
  ('labelbox', 'Labelbox', 'greenhouse', 'labelbox', '{}'::jsonb),
  ('marqeta', 'Marqeta', 'greenhouse', 'marqeta', '{}'::jsonb),
  ('mixpanel', 'Mixpanel', 'greenhouse', 'mixpanel', '{}'::jsonb),
  ('nextdoor', 'Nextdoor', 'greenhouse', 'nextdoor', '{}'::jsonb),
  ('okta', 'Okta', 'greenhouse', 'okta', '{}'::jsonb),
  ('opentable', 'OpenTable', 'greenhouse', 'opentable', '{}'::jsonb),
  ('pendo', 'Pendo', 'greenhouse', 'pendo', '{}'::jsonb),
  ('postman', 'Postman', 'greenhouse', 'postman', '{}'::jsonb),
  ('roblox', 'Roblox', 'greenhouse', 'roblox', '{}'::jsonb),
  ('roku', 'Roku', 'greenhouse', 'roku', '{}'::jsonb),
  ('thumbtack', 'Thumbtack', 'greenhouse', 'thumbtack', '{}'::jsonb),
  ('udemy', 'Udemy', 'greenhouse', 'udemy', '{}'::jsonb),
  ('unity', 'Unity', 'greenhouse', 'unity3d', '{}'::jsonb),
  ('upstart', 'Upstart', 'greenhouse', 'upstart', '{}'::jsonb),
  ('webflow', 'Webflow', 'greenhouse', 'webflow', '{}'::jsonb),
  ('wikimedia', 'Wikimedia Foundation', 'greenhouse', 'wikimedia', '{}'::jsonb),
  ('zoominfo', 'ZoomInfo', 'greenhouse', 'zoominfo', '{}'::jsonb),
  ('latitude-ai', 'Latitude AI', 'greenhouse', 'latitude', '{}'::jsonb),
  ('mistral', 'Mistral AI', 'ashby', 'mistral', '{}'::jsonb),
  ('deel', 'Deel', 'ashby', 'deel', '{}'::jsonb),
  ('figma', 'Figma', 'greenhouse', 'figma', '{}'::jsonb),
  ('supabase', 'Supabase', 'ashby', 'supabase', '{}'::jsonb),
  ('planetscale', 'PlanetScale', 'ashby', 'planetscale', '{}'::jsonb),
  ('resend', 'Resend', 'ashby', 'resend', '{}'::jsonb),
  ('cal', 'Cal.com', 'ashby', 'cal', '{}'::jsonb),
  ('neon', 'Neon', 'ashby', 'neon', '{}'::jsonb),
  ('orb', 'Orb', 'ashby', 'orb', '{}'::jsonb),
  ('clerk', 'Clerk', 'ashby', 'clerk', '{}'::jsonb),
  ('raycast', 'Raycast', 'ashby', 'raycast', '{}'::jsonb),
  ('drata', 'Drata', 'ashby', 'drata', '{}'::jsonb),
  ('groq', 'Groq', 'ashby', 'groq', '{}'::jsonb),
  ('cerebras', 'Cerebras', 'ashby', 'cerebras', '{}'::jsonb),
  ('together-ai', 'Together AI', 'ashby', 'together', '{}'::jsonb),
  ('mongodb', 'MongoDB', 'greenhouse', 'mongodb', '{}'::jsonb),
  ('new-relic', 'New Relic', 'greenhouse', 'newrelic', '{}'::jsonb),
  ('samsara', 'Samsara', 'greenhouse', 'samsara', '{}'::jsonb),
  ('riot-games', 'Riot Games', 'greenhouse', 'riotgames', '{}'::jsonb),
  ('naughty-dog', 'Naughty Dog', 'greenhouse', 'naughtydog', '{}'::jsonb),
  ('insomniac', 'Insomniac Games', 'greenhouse', 'insomniac', '{}'::jsonb),
  ('block', 'Block', 'greenhouse', 'block', '{}'::jsonb),
  ('adyen', 'Adyen', 'greenhouse', 'adyen', '{}'::jsonb),
  ('brex', 'Brex', 'greenhouse', 'brex', '{}'::jsonb),
  ('stability-ai', 'Stability AI', 'greenhouse', 'stabilityai', '{}'::jsonb),
  ('runway', 'Runway', 'greenhouse', 'runwayml', '{}'::jsonb),
  ('xai', 'xAI', 'greenhouse', 'xai', '{}'::jsonb),
  ('jetbrains', 'JetBrains', 'greenhouse', 'jetbrains', '{}'::jsonb),
  ('box', 'Box', 'greenhouse', 'boxinc', '{}'::jsonb),
  ('coreweave', 'CoreWeave', 'greenhouse', 'coreweave', '{}'::jsonb),
  ('runpod', 'RunPod', 'greenhouse', 'runpod', '{}'::jsonb),
  ('vast-ai', 'Vast.ai', 'greenhouse', 'vastai', '{}'::jsonb),
  ('snyk', 'Snyk', 'ashby', 'snyk', '{}'::jsonb),
  ('crowdstrike', 'CrowdStrike', 'ashby', 'crowdstrike', '{}'::jsonb),
  ('1password', '1Password', 'ashby', '1password', '{}'::jsonb),
  ('loom', 'Loom', 'ashby', 'loom', '{}'::jsonb),
  ('miro', 'Miro', 'ashby', 'miro', '{}'::jsonb),
  ('canva', 'Canva', 'ashby', 'canva', '{}'::jsonb),
  ('monday', 'monday.com', 'ashby', 'monday', '{}'::jsonb),
  ('fly', 'Fly.io', 'ashby', 'fly', '{}'::jsonb),
  ('render', 'Render', 'ashby', 'render', '{}'::jsonb),
  ('railway', 'Railway', 'ashby', 'railway', '{}'::jsonb),
  ('turso', 'Turso', 'ashby', 'turso', '{}'::jsonb),
  ('tinybird', 'Tinybird', 'ashby', 'tinybird', '{}'::jsonb),
  ('motherduck', 'MotherDuck', 'ashby', 'motherduck', '{}'::jsonb),
  ('clickup', 'ClickUp', 'ashby', 'clickup', '{}'::jsonb),
  ('axiom', 'Axiom', 'ashby', 'axiom', '{}'::jsonb),
  ('hightouch', 'Hightouch', 'ashby', 'hightouch', '{}'::jsonb),
  ('airbyte', 'Airbyte', 'ashby', 'airbyte', '{}'::jsonb),
  ('prefect', 'Prefect', 'ashby', 'prefect', '{}'::jsonb),
  ('dagster', 'Dagster', 'ashby', 'dagster', '{}'::jsonb),
  ('modal', 'Modal', 'ashby', 'modal', '{}'::jsonb),
  ('target', 'Target', 'workday', 'targetCareers', '{"default_filters": {"appliedFacets": {"jobFamilyGroup": ["daccab9f1d25018677ebcc363457460e", "daccab9f1d2501682445c5363457210e", "daccab9f1d250100d8b2c1363457f90d", "daccab9f1d2501e71ae8c3363457180e"]}}, "wd_company": "target", "wd_instance": 5}'::jsonb),
  ('dell', 'Dell', 'workday', 'External', '{"default_filters": {"appliedFacets": {"Location_Country": ["bc33aa3152ec42d4995f4791a106ed09"]}}, "wd_company": "dell", "wd_instance": 1}'::jsonb),
  ('intel', 'Intel', 'workday', 'External', '{"default_filters": {"appliedFacets": {"jobFamilyGroup": ["ace7a3d23b7e01a0544279031a0ec85c", "c37a9eaa90371000c6fd2261025d0000", "c37a9eaa90371000c6fd29069de10000", "a55ea4dd831d1000c6fce5a0c4d30000", "dc8bf79476611087d67b36517cf17036"]}}, "wd_company": "intel", "wd_instance": 1}'::jsonb),
  ('one-medical', 'One Medical', 'greenhouse', 'onemedical', '{}'::jsonb),
  ('cockroach-labs', 'Cockroach Labs', 'greenhouse', 'cockroachlabs', '{}'::jsonb),
  ('singlestore', 'SingleStore', 'greenhouse', 'singlestore', '{}'::jsonb),
  ('rubrik', 'Rubrik', 'greenhouse', 'rubrik', '{}'::jsonb),
  ('micron', 'Micron', 'eightfold', 'micron', '{"base_url": "https://micron.eightfold.ai", "default_filters": {"location": "United States"}, "domain": "micron.com"}'::jsonb),
  ('netflix', 'Netflix', 'eightfold_v2', 'netflix', '{"base_url": "https://explore.jobs.netflix.net", "domain": "netflix.com"}'::jsonb),
  ('qualcomm', 'Qualcomm', 'eightfold_v2', 'qualcomm', '{"base_url": "https://careers.qualcomm.com", "domain": "qualcomm.com"}'::jsonb),
  ('netapp', 'NetApp', 'eightfold_v2', 'netapp', '{"base_url": "https://careers.netapp.com", "domain": "netapp.com"}'::jsonb),
  ('lyft', 'Lyft', 'greenhouse', 'lyft', '{}'::jsonb),
  ('pinterest', 'Pinterest', 'greenhouse', 'pinterest', '{}'::jsonb),
  ('squarespace', 'Squarespace', 'greenhouse', 'squarespace', '{}'::jsonb),
  ('grammarly', 'Grammarly', 'greenhouse', 'grammarly', '{}'::jsonb),
  ('calendly', 'Calendly', 'greenhouse', 'calendly', '{}'::jsonb),
  ('intercom', 'Intercom', 'greenhouse', 'intercom', '{}'::jsonb),
  ('lucid-motors', 'Lucid Motors', 'greenhouse', 'lucidmotors', '{}'::jsonb),
  ('oscar-health', 'Oscar Health', 'greenhouse', 'oscar', '{}'::jsonb),
  ('relativity', 'Relativity', 'greenhouse', 'relativity', '{}'::jsonb),
  ('scopely', 'Scopely', 'greenhouse', 'scopely', '{}'::jsonb),
  ('motional', 'Motional', 'greenhouse', 'motional', '{}'::jsonb),
  ('nuro', 'Nuro', 'greenhouse', 'nuro', '{}'::jsonb),
  ('seatgeek', 'SeatGeek', 'greenhouse', 'seatgeek', '{}'::jsonb),
  ('apollo-io', 'Apollo.io', 'greenhouse', 'apolloio', '{}'::jsonb),
  ('carvana', 'Carvana', 'greenhouse', 'carvana', '{}'::jsonb),
  ('flatiron-health', 'Flatiron Health', 'greenhouse', 'flatironhealth', '{}'::jsonb),
  ('snorkel-ai', 'Snorkel AI', 'greenhouse', 'snorkelai', '{}'::jsonb),
  ('lattice', 'Lattice', 'greenhouse', 'lattice', '{}'::jsonb),
  ('wealthfront', 'Wealthfront', 'lever', 'wealthfront', '{}'::jsonb),
  ('color-health', 'Color Health', 'lever', 'color', '{}'::jsonb),
  ('black-forest-labs', 'Black Forest Labs', 'greenhouse', 'blackforestlabs', '{}'::jsonb),
  ('applied-intuition', 'Applied Intuition', 'greenhouse', 'appliedintuition', '{}'::jsonb),
  ('wayve', 'Wayve', 'greenhouse', 'wayve', '{}'::jsonb),
  ('assemblyai', 'AssemblyAI', 'greenhouse', 'assemblyai', '{}'::jsonb),
  ('hebbia', 'Hebbia', 'greenhouse', 'hebbia', '{}'::jsonb),
  ('augment-code', 'Augment Code', 'greenhouse', 'augmentcomputing', '{}'::jsonb),
  ('sourcegraph', 'Sourcegraph', 'greenhouse', 'sourcegraph91', '{}'::jsonb),
  ('abnormal-security', 'Abnormal Security', 'greenhouse', 'abnormalsecurity', '{}'::jsonb),
  ('tailscale', 'Tailscale', 'greenhouse', 'tailscale', '{}'::jsonb),
  ('lightning-ai', 'Lightning AI', 'greenhouse', 'lightningai', '{}'::jsonb),
  ('beautiful-ai', 'Beautiful.ai', 'greenhouse', 'beautifulai', '{}'::jsonb),
  ('goat-group', 'GOAT Group', 'greenhouse', 'goatgroup', '{}'::jsonb),
  ('nova-credit', 'Nova Credit', 'greenhouse', 'novacredit', '{}'::jsonb),
  ('emergent-ai', 'Emergent AI', 'greenhouse', 'emergentlabsinc', '{}'::jsonb),
  ('skydio', 'Skydio', 'greenhouse', 'skydio', '{}'::jsonb),
  ('character-ai', 'Character AI', 'ashby', 'character', '{}'::jsonb),
  ('cognition', 'Cognition', 'ashby', 'cognition', '{}'::jsonb),
  ('elevenlabs', 'ElevenLabs', 'ashby', 'elevenlabs', '{}'::jsonb),
  ('harvey', 'Harvey', 'ashby', 'harvey', '{}'::jsonb),
  ('suno', 'Suno', 'ashby', 'suno', '{}'::jsonb),
  ('pika', 'Pika', 'ashby', 'pika', '{}'::jsonb),
  ('windsurf', 'Windsurf', 'ashby', 'Windsurf', '{}'::jsonb),
  ('deepgram', 'Deepgram', 'ashby', 'Deepgram', '{}'::jsonb),
  ('poolside', 'Poolside', 'ashby', 'poolside', '{}'::jsonb),
  ('ideogram', 'Ideogram', 'ashby', 'ideogram', '{}'::jsonb),
  ('magic', 'Magic', 'ashby', 'magic.dev', '{}'::jsonb),
  ('writer', 'Writer', 'ashby', 'writer', '{}'::jsonb),
  ('evenup', 'EvenUp', 'ashby', 'evenup', '{}'::jsonb),
  ('pinecone', 'Pinecone', 'ashby', 'pinecone', '{}'::jsonb),
  ('weaviate', 'Weaviate', 'ashby', 'weaviate', '{}'::jsonb),
  ('lancedb', 'LanceDB', 'ashby', 'lancedb', '{}'::jsonb),
  ('convex', 'Convex', 'ashby', 'convex-dev', '{}'::jsonb),
  ('deepl', 'DeepL', 'ashby', 'DeepL', '{}'::jsonb),
  ('duckduckgo', 'DuckDuckGo', 'ashby', 'duck-duck-go', '{}'::jsonb),
  ('livekit', 'LiveKit', 'ashby', 'livekit', '{}'::jsonb),
  ('sesame', 'Sesame', 'ashby', 'sesame', '{}'::jsonb),
  ('cleric', 'Cleric', 'ashby', 'cleric', '{}'::jsonb),
  ('meticulous', 'Meticulous', 'ashby', 'meticulous', '{}'::jsonb),
  ('braintrust', 'Braintrust', 'ashby', 'Braintrust', '{}'::jsonb),
  ('shield-ai', 'Shield AI', 'lever', 'shieldai', '{}'::jsonb),
  ('wordware', 'Wordware', 'ashby', 'wordware.ai', '{}'::jsonb),
  ('nango', 'Nango', 'ashby', 'Nango', '{}'::jsonb),
  ('verge-genomics', 'Verge Genomics', 'lever', 'vergegenomics', '{}'::jsonb),
  ('smartsheet', 'Smartsheet', 'greenhouse', 'smartsheet', '{}'::jsonb),
  ('textio', 'Textio', 'greenhouse', 'textio', '{}'::jsonb),
  ('commerceiq', 'CommerceIQ', 'greenhouse', 'commerceiq', '{}'::jsonb),
  ('hyperproof', 'Hyperproof', 'greenhouse', 'hyperproof', '{}'::jsonb),
  ('temporal', 'Temporal', 'greenhouse', 'temporal', '{}'::jsonb),
  ('truveta', 'Truveta', 'greenhouse', 'truveta', '{}'::jsonb),
  ('carbon-robotics', 'Carbon Robotics', 'greenhouse', 'carbonrobotics', '{}'::jsonb),
  ('agility-robotics', 'Agility Robotics', 'greenhouse', 'agilityrobotics', '{}'::jsonb),
  ('offerup', 'OfferUp', 'greenhouse', 'offerup', '{}'::jsonb),
  ('bungie', 'Bungie', 'greenhouse', 'bungie', '{}'::jsonb),
  ('nintendo', 'Nintendo of America', 'greenhouse', 'nintendo', '{}'::jsonb),
  ('flexe', 'Flexe', 'greenhouse', 'flexe', '{}'::jsonb),
  ('terrapower', 'TerraPower', 'greenhouse', 'terrapowerllc', '{}'::jsonb),
  ('karat', 'Karat', 'greenhouse', 'karat', '{}'::jsonb),
  ('rover', 'Rover', 'lever', 'rover', '{}'::jsonb),
  ('alphasense', 'AlphaSense', 'greenhouse', 'alphasense', '{}'::jsonb),
  ('attentive', 'Attentive', 'greenhouse', 'attentive', '{}'::jsonb),
  ('celonis', 'Celonis', 'greenhouse', 'celonis', '{}'::jsonb),
  ('druva', 'Druva', 'greenhouse', 'druva', '{}'::jsonb),
  ('appsflyer', 'AppsFlyer', 'greenhouse', 'appsflyer', '{}'::jsonb),
  ('moveworks', 'Moveworks', 'greenhouse', 'moveworks', '{}'::jsonb),
  ('figure-ai', 'Figure AI', 'greenhouse', 'figureai', '{}'::jsonb),
  ('fireworks-ai', 'Fireworks AI', 'greenhouse', 'fireworksai', '{}'::jsonb),
  ('fal', 'fal', 'greenhouse', 'fal', '{}'::jsonb),
  ('heygen', 'HeyGen', 'greenhouse', 'heygen', '{}'::jsonb),
  ('chainguard', 'Chainguard', 'greenhouse', 'chainguard', '{}'::jsonb),
  ('merge', 'Merge', 'greenhouse', 'merge', '{}'::jsonb),
  ('lovable', 'Lovable', 'greenhouse', 'lovable', '{}'::jsonb),
  ('world-labs', 'World Labs', 'greenhouse', 'worldlabs', '{}'::jsonb),
  ('thinking-machines', 'Thinking Machines Lab', 'greenhouse', 'thinkingmachines', '{}'::jsonb),
  ('charlie-health', 'Charlie Health', 'greenhouse', 'charliehealth', '{}'::jsonb),
  ('kalshi', 'Kalshi', 'greenhouse', 'kalshi', '{}'::jsonb),
  ('decagon', 'Decagon', 'ashby', 'decagon', '{}'::jsonb),
  ('reflection-ai', 'Reflection AI', 'ashby', 'reflectionai', '{}'::jsonb),
  ('replicate', 'Replicate', 'ashby', 'replicate', '{}'::jsonb),
  ('sierra-ai', 'Sierra AI', 'ashby', 'sierra', '{}'::jsonb),
  ('ssi', 'Safe Superintelligence', NULL, NULL, '{}'::jsonb),
  ('wandb', 'Weights & Biases', 'lever', 'wandb', '{}'::jsonb),
  ('harness', 'Harness', 'greenhouse', 'harnessinc', '{}'::jsonb),
  ('langchain', 'LangChain', 'ashby', 'langchain', '{}'::jsonb),
  ('openevidence', 'OpenEvidence', 'ashby', 'openevidence', '{}'::jsonb),
  ('hippocratic-ai', 'Hippocratic AI', 'ashby', 'Hippocratic AI', '{}'::jsonb),
  ('dust', 'Dust', 'ashby', 'dust', '{}'::jsonb),
  ('relevance-ai', 'Relevance AI', 'ashby', 'relevanceai', '{}'::jsonb),
  ('adept-ai', 'Adept AI', 'ashby', 'adept.ai', '{}'::jsonb),
  ('coda', 'Coda', 'greenhouse', 'coda', '{}'::jsonb),
  ('encord', 'Encord', 'lever', 'CordTechnologies', '{}'::jsonb),
  ('zed', 'Zed', NULL, NULL, '{}'::jsonb),
  ('statsig', 'Statsig', 'ashby', 'statsig', '{}'::jsonb),
  ('chronosphere', 'Chronosphere', 'ashby', 'chronospherejobs', '{}'::jsonb),
  ('incident-io', 'incident.io', 'ashby', 'incident', '{}'::jsonb),
  ('stytch', 'Stytch', 'ashby', 'stytch', '{}'::jsonb),
  ('workos', 'WorkOS', 'lever', 'workos', '{}'::jsonb),
  ('sardine', 'Sardine', 'ashby', 'sardine', '{}'::jsonb),
  ('kong', 'Kong', 'ashby', 'kong', '{}'::jsonb),
  ('n8n', 'n8n', 'ashby', 'n8n', '{}'::jsonb),
  ('union-ai', 'Union.ai', 'ashby', 'Union', '{}'::jsonb),
  ('unit', 'Unit', 'ashby', 'unit', '{}'::jsonb),
  ('devrev', 'DevRev', 'greenhouse', 'devrev', '{}'::jsonb),
  ('zapier', 'Zapier', 'greenhouse', 'zapier', '{}'::jsonb),
  ('lithic', 'Lithic', 'greenhouse', 'lithic', '{}'::jsonb),
  ('tray-io', 'Tray.io', 'greenhouse', 'trayio', '{}'::jsonb),
  ('mx', 'MX', 'workday', 'EXT-MX', '{"wd_company": "mx", "wd_instance": 1}'::jsonb),
  ('descope', 'Descope', NULL, NULL, '{}'::jsonb),
  ('port', 'Port', NULL, NULL, '{}'::jsonb),
  ('moov', 'Moov', NULL, NULL, '{}'::jsonb),
  ('teller', 'Teller', NULL, NULL, '{}'::jsonb),
  ('make', 'Make', NULL, NULL, '{}'::jsonb),
  ('7ai', '7AI', 'ashby', 'sevenai', '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Greylock", "careers_url": "https://jobs.ashbyhq.com/sevenai", "headcount": "11-50"}}'::jsonb),
  ('abacus-ai', 'Abacus.AI', NULL, NULL, '{"metadata": {"stage": "Series D+", "ai_focused": true, "source_vc": "Coatue", "careers_url": "https://abacus.ai/jobs", "headcount": "100-200"}}'::jsonb),
  ('abridge', 'Abridge', 'ashby', 'abridge', '{"metadata": {"stage": "Series C", "ai_focused": true, "source_vc": "Bessemer Venture Partners", "careers_url": "https://jobs.ashbyhq.com/abridge", "headcount": "200-500"}}'::jsonb),
  ('ada', 'Ada', 'greenhouse', 'ada18', '{"metadata": {"stage": "Series C", "ai_focused": true, "source_vc": "Bessemer Venture Partners", "careers_url": "https://job-boards.greenhouse.io/ada18", "headcount": "500+"}}'::jsonb),
  ('ai21-labs', 'AI21 Labs', NULL, NULL, '{"metadata": {"stage": "Series D", "ai_focused": true, "source_vc": "Coatue", "careers_url": "https://www.ai21.com/careers", "headcount": "200-300"}}'::jsonb),
  ('airops', 'AirOps', 'ashby', 'airops', '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "Greylock", "careers_url": "https://www.airops.com/careers", "headcount": "30-50"}}'::jsonb),
  ('aisera', 'Aisera', 'greenhouse', 'aiserajobs', '{"metadata": {"stage": "Series D", "ai_focused": true, "source_vc": "Menlo Ventures", "careers_url": "https://job-boards.greenhouse.io/aiserajobs", "headcount": "200-500"}}'::jsonb),
  ('alloy', 'Alloy', 'greenhouse', 'alloy', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Bessemer Venture Partners", "careers_url": "https://boards.greenhouse.io/embed/job_board?for=alloy", "headcount": "300-500"}}'::jsonb),
  ('amp-robotics', 'AMP Robotics', 'greenhouse', 'ampsortation', '{"metadata": {"stage": "Series D+", "ai_focused": true, "source_vc": "Sequoia Capital", "careers_url": "https://job-boards.greenhouse.io/ampsortation", "headcount": "200-500"}}'::jsonb),
  ('anrok', 'Anrok', 'ashby', 'anrok', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Sequoia Capital", "careers_url": "https://jobs.ashbyhq.com/anrok", "headcount": "50-100"}}'::jsonb),
  ('anterior', 'Anterior', 'ashby', 'anterior', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Sequoia Capital", "careers_url": "https://jobs.ashbyhq.com/anterior", "headcount": "50-100"}}'::jsonb),
  ('apiiro', 'Apiiro', 'greenhouse', 'apiiro', '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "Greylock", "careers_url": "https://job-boards.greenhouse.io/apiiro", "headcount": "100-200"}}'::jsonb),
  ('appzen', 'AppZen', NULL, NULL, '{"metadata": {"stage": "Series C+", "ai_focused": true, "source_vc": "Coatue", "careers_url": "https://www.appzen.com/careers", "headcount": "200-400"}}'::jsonb),
  ('aqua-security', 'Aqua Security', NULL, NULL, '{"metadata": {"stage": "Series E", "ai_focused": false, "source_vc": "Lightspeed", "careers_url": "https://www.aquasec.com/about-us/careers/", "headcount": "200-500"}}'::jsonb),
  ('benchling', 'Benchling', 'greenhouse', 'benchling', '{"metadata": {"stage": "Series F", "ai_focused": false, "source_vc": "Benchmark", "careers_url": "https://job-boards.greenhouse.io/benchling", "headcount": "500-1000"}}'::jsonb),
  ('betterup', 'BetterUp', 'ashby', 'betterup', '{"metadata": {"stage": "Series E", "ai_focused": false, "source_vc": "Lightspeed", "careers_url": "https://jobs.ashbyhq.com/betterup", "headcount": "500+"}}'::jsonb),
  ('buildops', 'BuildOps', 'greenhouse', 'buildops', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Founders Fund", "careers_url": "https://boards.greenhouse.io/buildops", "headcount": "200-500"}}'::jsonb),
  ('builder-io', 'Builder.io', 'greenhouse', 'builder', '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "Greylock", "careers_url": "https://job-boards.greenhouse.io/builder", "headcount": "50-100"}}'::jsonb),
  ('camber-health', 'Camber Health', 'lever', 'camber', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Y Combinator", "careers_url": "https://jobs.lever.co/camber", "headcount": "50-100"}}'::jsonb),
  ('captions', 'Captions', 'greenhouse', 'captions', '{"metadata": {"stage": "Series C", "ai_focused": true, "source_vc": "Sequoia Capital", "careers_url": "https://www.captions.ai/careers", "headcount": "50-200"}}'::jsonb),
  ('captivateiq', 'CaptivateIQ', 'lever', 'captivateiq', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Sequoia Capital", "careers_url": "https://jobs.lever.co/captivateiq", "headcount": "200-500"}}'::jsonb),
  ('cartesia', 'Cartesia', 'ashby', 'cartesia', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Conviction Partners", "careers_url": "https://jobs.ashbyhq.com/cartesia", "headcount": "50-100"}}'::jsonb),
  ('censys', 'Censys', 'greenhouse', 'censys', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Greylock", "careers_url": "https://job-boards.greenhouse.io/censys", "headcount": "100-200"}}'::jsonb),
  ('chainalysis', 'Chainalysis', 'ashby', 'chainalysis-careers', '{"metadata": {"stage": "Series F", "ai_focused": false, "source_vc": "Benchmark", "careers_url": "https://jobs.ashbyhq.com/chainalysis-careers", "headcount": "500-1000"}}'::jsonb),
  ('clickhouse', 'ClickHouse', 'greenhouse', 'clickhouse', '{"metadata": {"stage": "Series D", "ai_focused": false, "source_vc": "Lightspeed", "careers_url": "https://job-boards.greenhouse.io/clickhouse", "headcount": "300-500"}}'::jsonb),
  ('clipboard-health', 'Clipboard Health', 'ashby', 'clipboard', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "IVP", "careers_url": "https://jobs.ashbyhq.com/clipboard", "headcount": "500+"}}'::jsonb),
  ('cogent-security', 'Cogent Security', 'ashby', 'cogent-security', '{"metadata": {"stage": "Seed", "ai_focused": true, "source_vc": "Greylock", "careers_url": "https://jobs.ashbyhq.com/cogent-security", "headcount": "10-30"}}'::jsonb),
  ('common-room', 'Common Room', 'ashby', 'commonroom', '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "Greylock", "careers_url": "https://jobs.ashbyhq.com/commonroom", "headcount": "100-200"}}'::jsonb),
  ('conductorone', 'ConductorOne', 'ashby', 'conductorone', '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "Accel", "careers_url": "https://jobs.ashbyhq.com/conductorone", "headcount": "50-100"}}'::jsonb),
  ('coram-ai', 'Coram AI', 'ashby', 'coram-ai', '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Air Street Capital", "careers_url": "https://jobs.ashbyhq.com/coram-ai", "headcount": "20-50"}}'::jsonb),
  ('cortex', 'Cortex', 'greenhouse', 'cortex', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "IVP", "careers_url": "https://job-boards.greenhouse.io/cortex", "headcount": "100-200"}}'::jsonb),
  ('cresta', 'Cresta', 'greenhouse', 'cresta', '{"metadata": {"stage": "Series C", "ai_focused": true, "source_vc": "Greylock", "careers_url": "https://job-boards.greenhouse.io/cresta", "headcount": "100-200"}}'::jsonb),
  ('cribl', 'Cribl', 'greenhouse', 'cribl', '{"metadata": {"stage": "Series D+", "ai_focused": false, "source_vc": "Greylock", "careers_url": "https://job-boards.greenhouse.io/cribl", "headcount": "500-700"}}'::jsonb),
  ('dexterity', 'Dexterity', 'lever', 'dexterity', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Lightspeed", "careers_url": "https://jobs.lever.co/dexterity", "headcount": "100-200"}}'::jsonb),
  ('eightfold', 'Eightfold', 'eightfold', 'eightfold', '{"metadata": {"stage": "Series E", "ai_focused": true, "source_vc": "Lightspeed", "careers_url": "https://eightfold.ai/company/careers/", "headcount": "500+"}}'::jsonb),
  ('essential-ai', 'Essential AI', 'ashby', 'essentialai', '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Conviction Partners", "careers_url": "https://jobs.ashbyhq.com/essentialai", "headcount": "14-50"}}'::jsonb),
  ('everlaw', 'Everlaw', 'greenhouse', 'everlaw', '{"metadata": {"stage": "Series D", "ai_focused": false, "source_vc": "Menlo Ventures", "careers_url": "https://job-boards.greenhouse.io/everlaw", "headcount": "500+"}}'::jsonb),
  ('fieldguide', 'Fieldguide', 'ashby', 'fieldguide', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Y Combinator", "careers_url": "https://jobs.ashbyhq.com/fieldguide", "headcount": "50-100"}}'::jsonb),
  ('fireblocks', 'Fireblocks', 'greenhouse', 'fireblocks', '{"metadata": {"stage": "Series E", "ai_focused": false, "source_vc": "Spark Capital", "careers_url": "https://job-boards.greenhouse.io/fireblocks", "headcount": "500+"}}'::jsonb),
  ('flock-safety', 'Flock Safety', 'ashby', 'flocksafety', '{"metadata": {"stage": "Series E", "ai_focused": false, "source_vc": "Spark Capital", "careers_url": "https://jobs.ashbyhq.com/flocksafety", "headcount": "1000+"}}'::jsonb),
  ('flywire', 'Flywire', 'greenhouse', 'flywire2', '{"metadata": {"stage": "Public", "ai_focused": false, "source_vc": "Spark Capital", "careers_url": "https://boards.greenhouse.io/flywire2", "headcount": "1000+"}}'::jsonb),
  ('gamma', 'Gamma', 'lever', 'gamma', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "IVP", "careers_url": "https://jobs.lever.co/gamma", "headcount": "50-100"}}'::jsonb),
  ('gecko-robotics', 'Gecko Robotics', 'ashby', 'gecko-robotics', '{"metadata": {"stage": "Series D", "ai_focused": false, "source_vc": "Founders Fund", "careers_url": "https://jobs.ashbyhq.com/gecko-robotics", "headcount": "100-200"}}'::jsonb),
  ('hackerone', 'HackerOne', 'ashby', 'hackerone', '{"metadata": {"stage": "Series E", "ai_focused": false, "source_vc": "Benchmark", "careers_url": "https://jobs.ashbyhq.com/hackerone", "headcount": "200-500"}}'::jsonb),
  ('hadrian', 'Hadrian', 'ashby', 'hadrian-automation', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "a16z", "careers_url": "https://jobs.ashbyhq.com/hadrian-automation", "headcount": "200-500"}}'::jsonb),
  ('harper', 'Harper', 'ashby', 'harperinsure', '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Y Combinator", "careers_url": "https://jobs.ashbyhq.com/harperinsure", "headcount": "11-50"}}'::jsonb),
  ('hex', 'Hex', 'greenhouse', 'hextechnologies', '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "Amplify Partners", "careers_url": "https://boards.greenhouse.io/hextechnologies", "headcount": "50-100"}}'::jsonb),
  ('instawork', 'Instawork', 'greenhouse', 'instawork', '{"metadata": {"stage": "Series D", "ai_focused": true, "source_vc": "Y Combinator", "careers_url": "https://job-boards.greenhouse.io/instawork", "headcount": "200-500"}}'::jsonb),
  ('inworld-ai', 'Inworld AI', 'greenhouse', 'inworldai', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Lightspeed", "careers_url": "https://boards.greenhouse.io/inworldai", "headcount": "50-100"}}'::jsonb),
  ('kittl', 'Kittl', 'ashby', 'kittl', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "IVP", "careers_url": "https://jobs.ashbyhq.com/kittl", "headcount": "200+"}}'::jsonb),
  ('lightmatter', 'Lightmatter', 'greenhouse', 'lightmatter', '{"metadata": {"stage": "Series D", "ai_focused": true, "source_vc": "Spark Capital", "careers_url": "https://job-boards.greenhouse.io/lightmatter", "headcount": "200-500"}}'::jsonb),
  ('luma-ai', 'Luma AI', NULL, NULL, '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Amplify Partners", "careers_url": "https://jobs.gem.com/lumalabs-ai", "headcount": "50-80"}}'::jsonb),
  ('lumafield', 'Lumafield', 'lever', 'lumafield', '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "IVP", "careers_url": "https://jobs.lever.co/lumafield", "headcount": "100-200"}}'::jsonb),
  ('mercor', 'Mercor', 'ashby', 'mercor', '{"metadata": {"stage": "Series C", "ai_focused": true, "source_vc": "a16z", "careers_url": "https://jobs.ashbyhq.com/mercor", "headcount": "50-200"}}'::jsonb),
  ('mercury', 'Mercury', 'greenhouse', 'mercury', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Spark Capital", "careers_url": "https://job-boards.greenhouse.io/mercury", "headcount": "500+"}}'::jsonb),
  ('modern-treasury', 'Modern Treasury', 'ashby', 'moderntreasury', '{"metadata": {"stage": "Series D", "ai_focused": false, "source_vc": "Benchmark", "careers_url": "https://jobs.ashbyhq.com/moderntreasury", "headcount": "50-200"}}'::jsonb),
  ('motive', 'Motive', 'greenhouse', 'gomotive', '{"metadata": {"stage": "Series D+", "ai_focused": false, "source_vc": "IVP", "careers_url": "https://job-boards.greenhouse.io/gomotive", "headcount": "3000+"}}'::jsonb),
  ('newfront', 'Newfront', 'ashby', 'newfront', '{"metadata": {"stage": "Series D", "ai_focused": false, "source_vc": "Y Combinator", "careers_url": "https://jobs.ashbyhq.com/newfront", "headcount": "500-1000"}}'::jsonb),
  ('niantic', 'Niantic', 'greenhouse', 'niantic', '{"metadata": {"stage": "Series D+", "ai_focused": false, "source_vc": "Spark Capital", "careers_url": "https://job-boards.greenhouse.io/niantic", "headcount": "500+"}}'::jsonb),
  ('numeric', 'Numeric', 'ashby', 'numeric', '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "IVP", "careers_url": "https://jobs.ashbyhq.com/numeric", "headcount": "50-100"}}'::jsonb),
  ('omnea', 'Omnea', 'ashby', 'omnea', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Khosla Ventures", "careers_url": "https://jobs.ashbyhq.com/omnea", "headcount": "50-200"}}'::jsonb),
  ('osmo', 'Osmo', 'ashby', 'osmo', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Lux Capital", "careers_url": "https://jobs.ashbyhq.com/osmo", "headcount": "50-100"}}'::jsonb),
  ('persona', 'Persona', 'greenhouse', 'persona', '{"metadata": {"stage": "Series D", "ai_focused": false, "source_vc": "Founders Fund", "careers_url": "https://withpersona.com/careers", "headcount": "300-500"}}'::jsonb),
  ('physical-intelligence', 'Physical Intelligence', 'ashby', 'physicalintelligence', '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Khosla Ventures", "careers_url": "https://jobs.ashbyhq.com/physicalintelligence", "headcount": "11-50"}}'::jsonb),
  ('pigment', 'Pigment', 'lever', 'pigment', '{"metadata": {"stage": "Series D", "ai_focused": false, "source_vc": "IVP", "careers_url": "https://jobs.lever.co/pigment", "headcount": "500+"}}'::jsonb),
  ('podium', 'Podium', 'greenhouse', 'podium81', '{"metadata": {"stage": "Series D+", "ai_focused": true, "source_vc": "Y Combinator", "careers_url": "https://job-boards.greenhouse.io/podium81", "headcount": "1000-5000"}}'::jsonb),
  ('polyai', 'PolyAI', 'greenhouse', 'polyai', '{"metadata": {"stage": "Series C", "ai_focused": true, "source_vc": "Khosla Ventures", "careers_url": "https://job-boards.greenhouse.io/polyai", "headcount": "100-300"}}'::jsonb),
  ('pulumi', 'Pulumi', 'greenhouse', 'pulumicorporation', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Madrona Ventures", "careers_url": "https://job-boards.greenhouse.io/pulumicorporation", "headcount": "150-300"}}'::jsonb),
  ('qventus', 'Qventus', 'greenhouse', 'qventus', '{"metadata": {"stage": "Series D", "ai_focused": true, "source_vc": "Y Combinator", "careers_url": "https://job-boards.greenhouse.io/qventus", "headcount": "100-200"}}'::jsonb),
  ('rad-ai', 'Rad AI', 'ashby', 'radai', '{"metadata": {"stage": "Series C", "ai_focused": true, "source_vc": "Khosla Ventures", "careers_url": "https://jobs.ashbyhq.com/radai", "headcount": "100-200"}}'::jsonb),
  ('reka', 'Reka', 'ashby', 'reka', '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Radical Ventures", "careers_url": "https://jobs.ashbyhq.com/reka", "headcount": "50-100"}}'::jsonb),
  ('retool', 'Retool', 'greenhouse', 'retool', '{"metadata": {"stage": "Series D+", "ai_focused": false, "source_vc": "Sequoia Capital", "careers_url": "https://job-boards.greenhouse.io/retool", "headcount": "200-500"}}'::jsonb),
  ('sakana-ai', 'Sakana AI', NULL, NULL, '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Lux Capital", "careers_url": "https://sakana.ai/careers", "headcount": "50-80"}}'::jsonb),
  ('samaya-ai', 'Samaya AI', 'greenhouse', 'samayaai', '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Air Street Capital", "careers_url": "https://samaya.ai/careers", "headcount": "30-60"}}'::jsonb),
  ('scribe', 'Scribe', 'greenhouse', 'scribehow', '{"metadata": {"stage": "Series C", "ai_focused": true, "source_vc": "Amplify Partners", "careers_url": "https://scribe.com/careers", "headcount": "100-200"}}'::jsonb),
  ('semgrep', 'Semgrep', 'greenhouse', 'semgrep', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Felicis Ventures", "careers_url": "https://job-boards.greenhouse.io/semgrep", "headcount": "100-200"}}'::jsonb),
  ('stoke-space', 'Stoke Space', 'greenhouse', 'stokespacetechnologies', '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "Spark Capital", "careers_url": "https://boards.greenhouse.io/embed/job_board?for=stokespacetechnologies", "headcount": "100-300"}}'::jsonb),
  ('stord', 'Stord', 'greenhouse', 'stord21', '{"metadata": {"stage": "Series E", "ai_focused": false, "source_vc": "Founders Fund", "careers_url": "https://boards.greenhouse.io/stord21", "headcount": "200-500"}}'::jsonb),
  ('synthesia', 'Synthesia', 'ashby', 'synthesia', '{"metadata": {"stage": "Series D", "ai_focused": true, "source_vc": "Air Street Capital", "careers_url": "https://jobs.ashbyhq.com/synthesia", "headcount": "500+"}}'::jsonb),
  ('tennr', 'Tennr', 'ashby', 'tennr', '{"metadata": {"stage": "Series C", "ai_focused": true, "source_vc": "IVP", "careers_url": "https://jobs.ashbyhq.com/tennr", "headcount": "100-200"}}'::jsonb),
  ('the-bot-company', 'The Bot Company', 'ashby', 'thebotcompany', '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Spark Capital", "careers_url": "https://jobs.ashbyhq.com/thebotcompany", "headcount": "50-100"}}'::jsonb),
  ('traba', 'Traba', 'ashby', 'traba', '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Founders Fund", "careers_url": "https://jobs.ashbyhq.com/traba", "headcount": "100-200"}}'::jsonb),
  ('tractable', 'Tractable', NULL, NULL, '{"metadata": {"stage": "Series D+", "ai_focused": true, "source_vc": "Air Street Capital", "careers_url": "https://tractable.ai/careers", "headcount": "200-500"}}'::jsonb),
  ('twelve-labs', 'Twelve Labs', 'ashby', 'twelve-labs', '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Radical Ventures", "careers_url": "https://jobs.ashbyhq.com/twelve-labs", "headcount": "50-100"}}'::jsonb),
  ('varda-space-industries', 'Varda Space Industries', 'greenhouse', 'vardaspace', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Khosla Ventures", "careers_url": "https://job-boards.greenhouse.io/vardaspace", "headcount": "50-100"}}'::jsonb),
  ('waabi', 'Waabi', 'lever', 'waabi', '{"metadata": {"stage": "Series C", "ai_focused": true, "source_vc": "Radical Ventures", "careers_url": "https://jobs.lever.co/waabi", "headcount": "200-400"}}'::jsonb),
  ('alkira', 'Alkira', NULL, NULL, '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Sequoia Capital", "careers_url": "https://www.alkira.com/careers/", "headcount": "100-200"}}'::jsonb),
  ('bigpanda', 'BigPanda', NULL, NULL, '{"metadata": {"stage": "Series D", "ai_focused": true, "source_vc": "Sequoia Capital", "careers_url": "https://www.bigpanda.io/company/panda-way/jobs/", "headcount": "100-200"}}'::jsonb),
  ('bigeye', 'Bigeye', NULL, NULL, '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Sequoia Capital", "careers_url": "https://www.bigeye.com/careers", "headcount": "50-100"}}'::jsonb),
  ('cato-networks', 'Cato Networks', NULL, NULL, '{"metadata": {"stage": "Series G+", "ai_focused": false, "source_vc": "Greylock", "careers_url": "https://www.catonetworks.com/careers/", "headcount": "500+"}}'::jsonb),
  ('forward', 'Forward', NULL, NULL, '{"metadata": {"stage": "Series E", "ai_focused": false, "source_vc": "Khosla Ventures", "careers_url": "https://goforward.com/careers", "headcount": "200-500"}}'::jsonb),
  ('freenome', 'Freenome', NULL, NULL, '{"metadata": {"stage": "Series E", "ai_focused": false, "source_vc": "Founders Fund", "careers_url": "https://www.freenome.com/careers", "headcount": "200-500"}}'::jsonb),
  ('newlimit', 'NewLimit', 'greenhouse', 'newlimit', '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "Founders Fund", "careers_url": "https://www.newlimit.com/careers", "headcount": "11-50"}}'::jsonb),
  ('radiant-nuclear', 'Radiant Nuclear', NULL, NULL, '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Founders Fund", "careers_url": "https://www.radiantnuclear.com/careers", "headcount": "100-200"}}'::jsonb),
  ('synchron', 'Synchron', 'greenhouse', 'synchron', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Khosla Ventures", "careers_url": "https://synchron.com/careers", "headcount": "100-200"}}'::jsonb),
  ('caldera', 'Caldera', NULL, NULL, '{"metadata": {"stage": "Series A", "ai_focused": false, "source_vc": "Founders Fund", "careers_url": "https://www.caldera.xyz/careers", "headcount": "11-50"}}'::jsonb),
  ('sereact', 'Sereact', NULL, NULL, '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Air Street Capital", "careers_url": "https://sereact.ai/careers", "headcount": "50-100"}}'::jsonb),
  ('vizcom', 'Vizcom', NULL, NULL, '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Radical Ventures", "careers_url": "https://vizcom.com/careers", "headcount": "20-50"}}'::jsonb),
  ('eye-security', 'Eye Security', 'ashby', 'eye-security', '{"metadata": {"stage": "Series C", "ai_focused": false, "source_vc": "Bessemer Venture Partners", "careers_url": "https://www.eye.security/careers", "headcount": "200-300"}}'::jsonb),
  ('aiwyn', 'Aiwyn', NULL, NULL, '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "Bessemer Venture Partners", "careers_url": "https://www.aiwyn.ai/careers", "headcount": "50-100"}}'::jsonb),
  ('sublime-security', 'Sublime Security', NULL, NULL, '{"metadata": {"stage": "Series B", "ai_focused": false, "source_vc": "IVP", "careers_url": "https://careers.sublime.security", "headcount": "50-100"}}'::jsonb),
  ('recall-ai', 'Recall.ai', 'ashby', 'Recall', '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Y Combinator", "careers_url": "https://www.recall.ai/careers", "headcount": "11-50"}}'::jsonb),
  ('ataraxis', 'Ataraxis', NULL, NULL, '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Founders Fund", "careers_url": "https://www.ataraxis.ai/careers", "headcount": "11-50"}}'::jsonb),
  ('vivodyne', 'Vivodyne', NULL, NULL, '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Khosla Ventures", "careers_url": "https://www.vivodyne.com/careers", "headcount": "11-50"}}'::jsonb),
  ('basis', 'Basis', NULL, NULL, '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Khosla Ventures", "careers_url": "https://www.getbasis.ai/careers", "headcount": "11-50"}}'::jsonb),
  ('eikon-therapeutics', 'Eikon Therapeutics', NULL, NULL, '{"metadata": {"stage": "Series C+", "ai_focused": false, "source_vc": "Lux Capital", "careers_url": "https://eikontx.com/careers", "headcount": "200-300"}}'::jsonb),
  ('carbon', 'Carbon', 'greenhouse', 'carbon', '{"metadata": {"stage": "Series E", "ai_focused": false, "source_vc": "Sequoia Capital", "careers_url": "https://www.carbon3d.com/careers", "headcount": "500-1000"}}'::jsonb),
  ('axiamatic', 'Axiamatic', NULL, NULL, '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "Greylock", "careers_url": "https://www.axiamatic.com/", "headcount": "20-50"}}'::jsonb),
  ('venice', 'Venice', NULL, NULL, '{"metadata": {"stage": "Series A", "ai_focused": true, "source_vc": "IVP", "careers_url": null, "headcount": "11-50"}}'::jsonb),
  ('genlogs', 'GenLogs', NULL, NULL, '{"metadata": {"stage": "Series B", "ai_focused": true, "source_vc": "IVP", "careers_url": null, "headcount": "50-100"}}'::jsonb),
  ('inception-labs', 'Inception Labs', NULL, NULL, '{}'::jsonb),
  ('parafin', 'Parafin', 'ashby', 'parafin', '{}'::jsonb),
  ('bloomberg', 'Bloomberg', 'avature', 'bloomberg', '{"av_section": "careers"}'::jsonb),
  ('koch', 'Koch Industries', 'avature', 'koch', '{"av_section": "careers", "av_locale": "en_US"}'::jsonb),
  ('xerox', 'Xerox', 'avature', 'xerox', '{"av_section": "careers", "av_locale": "en_US"}'::jsonb),
  ('synopsys', 'Synopsys', 'avature', 'synopsys', '{"av_section": "careers"}'::jsonb),
  ('ally', 'Ally Financial', 'avature', 'ally', '{"av_section": "careers"}'::jsonb),
  ('broad-institute', 'Broad Institute', 'avature', 'broadinstitute', '{"av_section": "careers", "av_locale": "en_US"}'::jsonb),
  ('maximus', 'Maximus', 'avature', 'maximus', '{"av_section": "careers"}'::jsonb),
  ('deloitte', 'Deloitte', 'avature', 'deloittebe', '{"av_section": "careers", "av_locale": "en_US"}'::jsonb),
  ('walgreens', 'Walgreens', 'talentbrew', NULL, '{"tb_host": "jobs.walgreens.com", "tb_tenant_id": 1242}'::jsonb),
  ('wegmans', 'Wegmans', 'talentbrew', NULL, '{"tb_host": "jobs.wegmans.com", "tb_tenant_id": 1839}'::jsonb),
  ('comcast', 'Comcast', 'talentbrew', NULL, '{"tb_host": "jobs.comcast.com", "tb_tenant_id": 45483}'::jsonb),
  ('spectrum', 'Spectrum', 'talentbrew', NULL, '{"tb_host": "jobs.spectrum.com", "tb_tenant_id": 4673}'::jsonb),
  ('boeing', 'Boeing', 'talentbrew', NULL, '{"tb_host": "jobs.boeing.com", "tb_tenant_id": 185}'::jsonb),
  ('citi', 'Citi', 'talentbrew', NULL, '{"tb_host": "jobs.citi.com", "tb_tenant_id": 287}'::jsonb),
  ('pge', 'PG&E', 'talentbrew', NULL, '{"tb_host": "jobs.pge.com", "tb_tenant_id": 29673}'::jsonb)
ON CONFLICT (slug) DO NOTHING;

-- Backfill orphaned slugs from sync_status and jobs
INSERT INTO companies (slug, name, ats, board, config)
SELECT ss.company_slug, ss.company_slug, NULL, NULL, '{}'::jsonb
FROM sync_status ss
WHERE NOT EXISTS (SELECT 1 FROM companies c WHERE c.slug = ss.company_slug)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO companies (slug, name, ats, board, config)
SELECT DISTINCT j.company_slug, j.company_slug, NULL, NULL, '{}'::jsonb
FROM jobs j
WHERE NOT EXISTS (SELECT 1 FROM companies c WHERE c.slug = j.company_slug)
ON CONFLICT (slug) DO NOTHING;

-- Drop old FK (jobs -> sync_status)
ALTER TABLE jobs DROP CONSTRAINT IF EXISTS fk_jobs_company_slug;

-- Add new FKs (jobs -> companies, sync_status -> companies)
DO $$ BEGIN
    ALTER TABLE jobs
        ADD CONSTRAINT fk_jobs_company
        FOREIGN KEY (company_slug) REFERENCES companies(slug)
        DEFERRABLE INITIALLY DEFERRED;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE sync_status
        ADD CONSTRAINT fk_sync_status_company
        FOREIGN KEY (company_slug) REFERENCES companies(slug)
        DEFERRABLE INITIALLY DEFERRED;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;
